### ISSUE TITLE
Is DNR-326 compatable / partial compatable?

### ISSUE THREAD

**Issue by zlocate** [djon2003/DNS-323#6]
Is DNR-326 compatible / partial compatible with this guide?

**Comment by djon2003** [comment]
@zlocate 

Well, there is more memory on this device than the DNS-323. So, on this part it should be OK.

I would guess it would work.

I have been able to extract the kernel and ram disk from the latest firmware of the DNR-326 using [the tool for DNS-323](http://www.cyrius.com/debian/orion/d-link/dns-323/recovery/). That seems promising.

You can also ask the IRC channel below; they gave me a hand to accomplish this marvelous change!
irc://irc.debian.org/#debian-arm

You can also try installing fun_plug (see the branches 1.*) and connect via telnet to ensure some stuff. Because flashing with Debian, if you can't access via SSH after, you will have to recover using a serial connection (and the instructions I have are for DNS-323). Quickly, I didn't find instructions to add a serial port connection on the DNR-326. You could also verify if the [DNS-323 instructions](http://dns323.kood.org/hardware%3Aserial) would seem to be applicable.

Remember that this kind of operation is always risky (flashing) and there is no warranty you will not screw your device. Hence why I proceeded less risky to more risky.

Give me news! If it works, I'll add a list of supported device models. (It would make two, yes!!)

**Comment by djon2003** [comment]
@zlocate Did you have time to try?

**Comment by djon2003** [comment]
@zlocate As it makes a while, I will close this issue. If you had tried with this model and have time to tell me, you can reopen this issue, that would appreciated.
